 SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
		FROM EMP
		WHERE SAL IN(SELECT MAX(SAL)
				FROM EMP
				WHERE SAL<(SELECT MAX(SAL)
						FROM EMP
						WHERE SAL<(SELECT MAX(SAL)
								FROM EMP))))
/
